### PR TITLE
Fix for rasa_nlu #762

### PR DESCRIPTION
**Pull request by useready-andyv**
**Proposed changes**: Added code to handle attachments for slack channel with all additional tags 
Changes in files: 
rasa_core/channels/channel.py: New method send_attachment added.
rasa_core/channels/slack.py: New method send_attachment added. Added returns to all send methods to enable testing and to bubble up http status errors from slack api so Actions can handle the same.
dispatcher.py : split send_image_url and send_attachment as two separate methods.
tests/test_channels: Added tests with monkeypatch to validate changes made.
tests/test_dispatcher: Added tests to validate changes made.
 - ...

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by useready-andyv** [comment]
New pull request being added

**Comment by useready-andyv** [comment]
Please help in resolving conflict.

**Comment by tmbo** [comment]
Improving this is a great idea :+1: Some thoughts:
- do we really need `utter_image`, I can't see a difference to `utter_attachement`
- do you know what happened to the requirements file? did you change the linebreaks there?

**Comment by useready-andyv** [comment]
Dont need utter_image at all, removed that in  the last commit, will go back and check if everything is cleaned up

In requirements, I had to change version of one of the libraries as pip install was complaining that it could not find a version, will check and confirm the line

On a side note: what is your working env?
I am having a hard time making commits on a centos, vs code based system
Would love to hear what you are using, might make my life easier!

Thumb typed on a handheld, pardon the typos.
________________________________

**Comment by useready-andyv** [comment]
I have made the fixes and checked in code. 
utter_image_url is removed in dispatcher.py
Line breaks for requrements.txt is fixed, check for tensorflow library version reapplied.

Please merge when you get a chance.

**Comment by tmbo** [comment]
Thanks a lot for these improvements and additional tests :+1:

**Pull request merged**
