### PR TITLE
accepting remove_duplicates as a parameter to agent.train

### PR DESCRIPTION
**Pull request by npx**
**Proposed changes**:
- #54 `remove_duplicates` can be passed to `agent.train`

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

Is this PR about what you had in mind when formulating #54?
If not maybe you can give me some more insight on how you imagined this change to be :)
If yes I will move on to satisfy further contribution guidelines!

(Off-Topic: Hey Joey, I loved your talk on PyCon.DE!)

### CODE REVIEW

**Comment by tmbo** [comment]
@JoeyFaulkner mind to comment?

code is looking good, thanks :+1:

**Comment by tmbo** [comment]
I'd love to merge this, would you mind signing the contributor agreement? https://cla-assistant.io/RasaHQ/rasa_core

**Comment by npx** [comment]
@tmbo not a problem, if you are happy as is, feel free to merge, I signed the CLA :)

**Comment by tmbo** [comment]
Great, nice 🚀

**Pull request merged**
