### PR TITLE
adding typetest-pep8

### PR DESCRIPTION
**Pull request by alexissmirnov**
**Proposed changes**:
- `make test` requires `pytest-pep8` so i've added it

**Status (please check what you already did)**:
- [X] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by alexissmirnov** [comment]
I've signed the CLA as alexis@smirnov.ca and my GitHub account has an email associated with it (alexis@smirnov.ca)

Don't know what else I need to do to unblock this one

**Comment by akelad** [comment]
@alexissmirnov can I ask why you want to add pep8 to the requirements? we use pycodestyle now

**Comment by alexissmirnov** [comment]
@akelad I've added it because `make test` failed to run without it. Should I be changing `Makefile` instead?

**Comment by akelad** [comment]
no, this is all fixed in the rasa_nlu repo (which is where PRs go now, so i'm gonna close this). thanks though!

**Pull request closed without merging**
