### PR TITLE
Fix for issue #63 - Moodbot tutorial

### PR DESCRIPTION
**Pull request by gcreddy42**
**Proposed changes**:
- Changed the "greeting" intent in nlu.md file to "greet". The intent is referred as "greet" in domain and story files.

**Status (please check what you already did)**:
- [x] made PR ready for code review

### CODE REVIEW

**Comment by gcreddy42** [comment]
@tmbo Can you please review this PR?

**Comment by tmbo** [comment]
Yes on it. will get back to you in a minute (the problem is not reviewing the code 😉 )

**Comment by tmbo** [comment]
Looking good :+1: Can you please make sure to sign the CLA so we can get this merged? https://cla-assistant.io/RasaHQ/rasa_core

**Comment by gcreddy42** [comment]
@tmbo Signed. Thanks, Tom.

**Comment by tmbo** [comment]
Nice 🚀

**Pull request merged**
