### PR TITLE
Sklearn policy

### PR DESCRIPTION
**Pull request by benjamin-work**
**Proposed changes**:

Implement an sklearn policy (similar to `KerasPolicy`).

The sklearn policy supports any valid sklearn classifier, cross-validation and grid search. If the classifier allows for `partial_fit`, the sklearn policy supports online training.

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by tmbo** [comment]
@benjamin-work do you mind taking a look at the failing travis build before I do the review?

**Comment by benjamin-work** [comment]
It appears that the error is:

`
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'xdist' could not be loaded: (py 1.5.0 (/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages), Requirement.parse('py<1.5,>=1.4.33'), {'pytest'})!
`

which seems to be unrelated to my changes. Maybe you have an idea what the issue is?

**Comment by tmbo** [comment]
Mind merging in master? I have removed minconda in the latest version - so that already might fix the issue. If that doesn't fix it, I'll take a closer look at whats going wrong.

**Comment by benjamin-work** [comment]
Are we good now, are the codeclimate issues mandatory to fix?

**Comment by tmbo** [comment]
No, I think we are good to go - checked them and they are ok.

Thanks a lot for all the work you have put into this :rocket:

**Pull request merged**
