### PR TITLE
Graphviz removal

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed changes**:
- remove the (py)graphviz dependencies
- display the story graph within a html page instead of generating an image
- adapting the visualization feature of the interactive learning for that
- reuse the html template used for the visualization of the interactive learning
- adapt documentation etc to the new html approach

Command to test it out:
`python -m rasa_core.visualize -s examples/concertbot/data/stories.md -d examples/concertbot/domain.yml -o graph.html`

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog

### CODE REVIEW

**Comment by amn41** [comment]
I think we need to add pydot to the setup.py as well.

**Comment by amn41** [comment]
can confirm ff, safari still errors

**Comment by wochinge** [comment]
I fixed the issue with safari. It was actually some problems with the replacement which made the js processing fail for interactive learning.
I also moved and adapted the test case.

**Comment by tmbo** [comment]
works for me in safari, must be your old version @amn41 :D

**Pull request merged**
