### PR TITLE
WIP: log duplicate stories

### PR DESCRIPTION
**Pull request by wochinge**
**Proposed changes**:
- log duplicate stories

Things to do:
- [ ] check with checkpointed stories
- [ ] check if check for phase is required and potentially remove it

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by wochinge** [comment]
@tmbo To be honest, I am not a 100 percent sure what happens in the code around it. Currently every duplicate story gets logged twice. Any ideas how to avoid that?

**Review by tmbo — APPROVED** [review]
I think the code looks good, not sure though where the double logging comes from - maybe @Ghostvv has some more insights on that

**Comment by Ghostvv** [comment]
@wochinge didn't we try it together, and there were no double logging?

**Comment by wochinge** [comment]
@Ghostvv Yes, there was no double logging with you. But still have to test this out with checkpointed stories and other stuff is currently more important. Should also be easy to be ported.

**Pull request closed without merging**
