### PR TITLE
allow to specify a socket path

### PR DESCRIPTION
**Pull request by znat**
**Proposed changes**:
- All in the title

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Hey @znat thanks for submitting this PR! One question: isn't `/socket.io` always the path?

**Comment by znat** [comment]
@akelad `/socket.io/` is always the *default* path but you can specify a different path. Useful is a situations where the default route of the app hosting your webchat is of type `http://host/folder`. The socket url will always be `http://host` but the socket path will be `/folder/socket.io/`

**Comment by akelad** [comment]
there's also some pep8 checks that made the build fail, please fix those too

**Comment by znat** [comment]
I fixed the pep8. I am really wondering if keeping code lines length below 80 chars is really a code quality feature in 2018.
I also added the email address I committed with to my Github account but that doesn't seem to satisfy the CLA requirements. Not sure what to do here.

**Comment by akelad** [comment]
Hmm, you've followed these steps for adding the email address? https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user
and the <80 thing makes things easier to read

**Comment by znat** [comment]
CLA seems happy now :)

**Pull request merged**
