### PR TITLE
Tutorial restructuring

### PR DESCRIPTION
**Pull request by ricwo**
**Proposed changes**:
- restructuring of the tutorials

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by amn41** [comment]
@tmbo @ricwo I removed line numbers in f1a8d3603b205acf9e93a8d97a66cd46e0479fca because this causes a bunch of blank lines to be rendered. Supposedly [fixed](https://github.com/rtfd/sphinx_rtd_theme/issues/417) in latest rtd-theme but when I merged with our fork it didn't resolve the issue for me.

**Comment by tmbo** [comment]
Which empty lines do you mean? I can't see any at http://core.rasa.ai/tutorial_basics.html and I am not sure why that should have changed with this PR

**Comment by amn41** [comment]
@tmbo http://core.rasa.ai/master/tutorial_basics.html

**Comment by tmbo** [comment]
ok we had that before - this is not an issue of empty lines, the lines are just not aligned to the line numbers

**Comment by amn41** [comment]
what's the fix? shall I revert that commit then?

**Comment by tmbo** [comment]
Give me a sec, looking into it right now

**Comment by tmbo** [comment]
Ok @amn41 the fix got lost right here:

https://github.com/RasaHQ/rasa_core/commit/28e58421a374c3968ec5482aacddfde6806ca734#diff-5bef800b7655c038d4f6f2a972d7b354L1

not sure why though. Can you add these line to `docs/_static/custom.css` again (file got deleted in that commit put is present in master, just without these lines...)

**Pull request merged**
