### PR TITLE
Fixed bug originated due to FallbackPolicy max_history being None

### LINKED ISSUE #594: Using FallbackPolicy with agent.load_data() leads to an error
**Rasa Core version**: 0.10.0a2

**Python version**: 3.6

**Operating system** (windows, osx, ...): Linux Ubuntu 16.04

**Issue**:
File agent.py line 200 in the method load_data() of class Agent:
```     
 if hasattr(policy.featurizer, 'max_history'):
    max_max_history = max(policy.featurizer.max_history,
                                       max_max_history)
```
FallbackPolicy has attribute max_history but it is set to None in fallback.py. This causes error in the max function.

Simple solution:
```
if hasattr(policy.featurizer, 'max_history') and policy.featurizer.max_history!=None:
                max_max_history = max(policy.featurizer.max_history,
                                      max_max_history)
```

### PR DESCRIPTION
**Pull request by rusiaaman**
**Proposed changes**:
- Fixes #594 

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by Ghostvv** [comment]
Could you please try this PR: https://github.com/RasaHQ/rasa_core/pull/591, and check if Fallback policy works as expected?

**Comment by rusiaaman** [comment]
#591 fixes the problem in agent.py but one error still remains due to the following line in ensemble.py (line 101) class PolicyEnsemble method _max_histories:

`if isinstance(p.featurizer, MaxHistoryTrackerFeaturizer):`

Since the FallbackPolicy is missing the featurizer.

**Comment by Ghostvv** [comment]
Thank you for noticing this!

**Comment by rusiaaman** [comment]
Closing this since this issue is being addressed in #591

**Pull request closed without merging**
