### PR TITLE
switch to questionary

### PR DESCRIPTION
**Pull request by tmbo**
**Proposed changes**:
- switch from unmaintaned pyinquierer to questionary

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] updated the changelog

### CODE REVIEW

**Comment by wochinge** [comment]
@tmbo 
Getting this error when I select `continue` (using the master branch of `questionary`): 
```bash
? The bot wants to run 'action_listen', correct?  Yes
? Next user input (Ctr-c to abort):

Cancelled by user

? Do you want to stop?  Continue
2018-12-12 17:16:37 ERROR    rasa_core.server  - Caught an exception while logging message.
Traceback (most recent call last):
  File "/Users/rasa/Workspace/rasa_core/rasa_core/server.py", line 443, in log_message
    tracker = agent.log_message(usermsg)
  File "/Users/rasa/Workspace/rasa_core/rasa_core/agent.py", line 323, in log_message
    return processor.log_message(message)
  File "/Users/rasa/Workspace/rasa_core/rasa_core/processor.py", line 121, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "/Users/rasa/Workspace/rasa_core/rasa_core/processor.py", line 259, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "/Users/rasa/Workspace/rasa_core/rasa_core/processor.py", line 241, in _parse_message
    if message.text.startswith(INTENT_MESSAGE_PREFIX):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by wochinge** [comment]
When I say `No` to `The bot wants to run 'utter_greet', correct?` it directly shows me this menu, but should show the predictions.
bildschirmfoto 2018-12-12 um 18 10 06

**Comment by tmbo** [comment]
@wochinge I've fixed the issues, would be great if you could take another look

**Comment by tmbo** [comment]
This wasn't an issue of this specific change (the issue was there before) - Nevertheless, I removed the validation, as there appears to be no easy way to do this kind of path validation without creating the file.

**Pull request merged**
