### PR TITLE
Wrong HTTP response code when updating model from server

### PR DESCRIPTION
**Pull request by znat**
**Proposed changes**:
- small doc thing

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Thanks for submitting the PR! But I think the 204 is correct? https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/agent.py#L139

**Comment by tmbo** [comment]
@znat is right though, it should probably rather be 304 instead of 204 (I think we should change the code to accept both and treat them the same way)

**Comment by znat** [comment]
204 is no content and 304 is not modified. I guess it depends on implementations so @tmbo's idea to support both is probably the best.

**Comment by akelad** [comment]
@znat is that a modification you'd be willing to add to the code?

**Comment by znat** [comment]
If you agree on the solution I can certainly submit a PR. I would also update the doc to mention both 204 and 304

**Comment by akelad** [comment]
yes, sounds good!

**Comment by znat** [comment]
Closing. See https://github.com/RasaHQ/rasa_core/pull/1307 instead

**Pull request closed without merging**
