### PR TITLE
Predict endpoint

### PR DESCRIPTION
**Pull request by JoeyFaulkner**
**Proposed changes**:
- added a predict endpoint where a list of applied actions can be passed and the next prediction is returned

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
great commit messages @JoeyFaulkner hahaha (what is a kebab case)

**Comment by tmbo** [comment]
Something like this is already present in the sdk version: https://github.com/RasaHQ/rasa_core/blob/dispatcher/rasa_core/server.py#L317

**Comment by JoeyFaulkner** [comment]
@tmbo No, this is a predict endpoint where you can pass any collection of events, it doesnt need to be tied to a particular sender

**Comment by tmbo** [comment]
ah alright, makes sense :+1: - can you please rebase from master or do you need any changes made on the sdk branch?

**Comment by tmbo** [comment]
This is still pulling in the changes from the event output branch. I am not sure what happened in the commit history there in the middle 

bildschirmfoto 2018-08-08 um 10 44 46

but it wasn't straightforward to rebase and you'd probably need to cherry pick your changes. Given that the changes are split across 40 commits I'd rather suggest you create a new branch and only apply the changes you want in the PR there.

**Comment by JoeyFaulkner** [comment]
@tmbo ok will do!

**Pull request closed without merging**
