### PR TITLE
Randomized initial sender_id in interactive.py to allow fresh training sessions upon start

### PR DESCRIPTION
**Pull request by smn-snkl**
According to #1339, in-memory tracker stores load previous sessions during interactive learning.

**Proposed changes**:
- Make initial sender_id random

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog

### CODE REVIEW

**Comment by smn-snkl** [comment]
@tmbo : According to what you suggested [here](https://github.com/RasaHQ/rasa_core/issues/1339#issuecomment-439884983) I added `sender_id=uuid.uuid4().hex` to the kwargs for the `_start_interactive_learning_io` thread. This way it shouldn't be initialized with the `UserMessage.DEFAULT_SENDER_ID`. Does that do the trick already?

**Comment by akelad** [comment]
Thanks for raising this PR ,we'll give it a review as soon as possible

**Comment by tmbo** [comment]
Do you mind adding a note about this change to the `Changelog.rst` before we merge this?

**Comment by smn-snkl** [comment]
@tmbo : Done. Sorry, for the delay.

**Comment by tmbo** [comment]
Awesome, thanks a lot :+1:

**Comment by smn-snkl** [comment]
@akelad @tmbo What are your plans on merging 0.12.x PRs into master? Was thinking about upgrading to 0.13 but I guess the benefits of this and maybe some other PRs would be "lost" then.

**Comment by tmbo** [comment]
@smn-snkl I just double checked, I don't think there are any changes on the 0.12.x branch that are not present on the master branch. Which changes are you worried about, the ones from this PR?

**Comment by smn-snkl** [comment]
Hmm, weird. I couldn't find this PR's changes in master, but you're right they're there. Guess I might have compared it with the wrong branch then. All good, thanks!

**Comment by tmbo** [comment]
no worries :+1:

**Pull request merged**
