### PR TITLE
Add RocketChat connector

### PR DESCRIPTION
**Pull request by izacristina**
Signed-off-by: Izabela Cardoso <cizabelacristina@gmail.com>
Signed-off-by: Matheus Miranda <matheusmirandalacerda@gmail.com>

**Proposed changes**:
- Added RocketChat connector 
- Updated docs/connector.rst 
- Updated CHANGELOG.rst

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
cool, thanks for this PR! We'll give it a review soon, in the meantime do you mind signing the CLA?

**Comment by MatheusFaria** [comment]
We've updated the connector code to support rocket's realtime API, but it seems that the rocket's lib does not work on python2.7
Since we also maintain this lib, we will fix this error in the next days

**Comment by MatheusFaria** [comment]
It is ready to be reviewed now. We got it working on python 2.7.
Any changes requested let us know :)

**Comment by tmbo** [comment]
Looking good, I made some more changes to adapt to the new structure. I also removed the typing indication for now: although I think it is neat, this should be solved in general for all channels that support it.

**Pull request merged**
