### PR TITLE
look for username attr rather than user 

### LINKED ISSUE #1120: JWT should look for 'username' field inside 'user' obj
**Rasa Core version**: master

**Issue**:
after decoding the JWT, we check for `data["user"]["user"]` but should be `data["user"]["username"]`

### PR DESCRIPTION
**Pull request by amn41**
**Proposed changes**:
- fixes #1120 

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by tmbo** [comment]
test needs to be fixed though before merging

**Comment by tmbo** [comment]
@amn41 for some reason the tokens still don't seem to be working

**Comment by amn41** [comment]
ok thanks I will look into it.

**Comment by tmbo** [comment]
don't we need to fix this anymore?

**Comment by amn41** [comment]
fixed here https://github.com/RasaHQ/rasa_core/pull/1139#issuecomment-427442301

**Comment by tmbo** [comment]
no the jwt change, was removed from that pr because of this one

**Pull request merged**
