### PR TITLE
test domain save from interactive training

### PR DESCRIPTION
**Pull request by tzolkincz**
**Proposed changes**:
- There is a bug with domain persistence from interactive learning. When domain is saved some default actions (which are not overridden) are added to the domain config file.
Scope of this PR is only to add test, to show buggy behavior and start discussion how this issue can be resolved.

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by tzolkincz** [comment]
@tmbo Thanks for pointing to `utils.read_json_file` :+1: 
And just to be sure, this test assumes that `moodbot` example *does not* override default `action_listen`.

**Comment by tzolkincz** [comment]
There is a link #1354 for related issue.

**Comment by tmbo** [comment]
Ok, now that we have a failing test - do you have some time to look into fixing the issue when dumping the domain?

**Comment by Ghostvv** [comment]
Thank you for adding the test, created the PR to fix it: https://github.com/RasaHQ/rasa_core/pull/1375

**Comment by Ghostvv** [comment]
@tzolkincz could you please merge the branch `merge-domain-fix` into yours and create the PR to this branch, so we could test it using your test

**Comment by Ghostvv** [comment]
thanks, but since we want to merge this bug fix to `0.12.x`, you need to `rebase` your branch

**Comment by tzolkincz** [comment]
@Ghostvv in progress :)

**Comment by Ghostvv** [comment]
Perfect thanks

**Comment by tzolkincz** [comment]
@Ghostvv merge with rebase is in PR #1377

**Pull request closed without merging**
