### PR TITLE
fix branch whitelist

### PR DESCRIPTION
**Pull request by amn41**
**Proposed changes**:
- don't match forked master branches

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [x] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by tmbo** [comment]
but does this really prevent forked masters? - I though the travis build configuration does that by not building the docs

**Comment by amn41** [comment]
well previously we were matching things like `username-master` which I presume are forks. spinxcontrib-versioning pulls every ref from remote before checking against the whitelist, so it's not so much about what travis builds but what's in the git remote

**Comment by tmbo** [comment]
right, I wasn't aware that the plugin is treating the `svc_whitelist_branches` as `.*master.*` - thought it would just do a `==`.

**Comment by amn41** [comment]
yep was also a surprise to me :)

**Pull request merged**
