### PR TITLE
webhook was not set previously

### PR DESCRIPTION
**Pull request by tiwari85aman**
telegram integration was not working prior because the webhook required for the integration was not set previously.

Now, the telegram integration is working correctly as expected

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by tiwari85aman** [comment]
@akelad is there anything else needed?

**Comment by tmbo** [comment]
Given that the return value is ignored for the function, it would be good to add some logging. Do you mind adding a `logger.info` in the success case and a `logger.warn` in the failure case?

**Comment by tiwari85aman** [comment]
@tmbo ok sure I will make those loggings. thanks for suggesting :+1:

**Comment by tiwari85aman** [comment]
@tmbo sir, please verify the changes of logger updat.

**Comment by tiwari85aman** [comment]
@tmbo is there something else required, apart from logger update?

**Comment by tmbo** [comment]
No looking good, thanks for the fix :+1:

**Pull request merged**
