### PR TITLE
Add max_event_history in tracker_store

### PR DESCRIPTION
**Pull request by harmekai**
**Proposed changes**:
- Implemented a pipe to set the attribute max_event_history of DialogueStateTracker in tracker_store.py
- Solves/inspired by https://github.com/RasaHQ/rasa_core/issues/1226 

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [x] updated the documentation
- [x] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
Thanks for submitting this PR - is it ready for review?

**Comment by harmekai** [comment]
@akelad yes it is ready for review

**Comment by harmekai** [comment]
@akelad this PR is ready for review

**Comment by akelad** [comment]
yep we're aware of it, it's in our backlog and we'll give it a review ASAP

**Comment by tmbo** [comment]
Just noticed it was missing tests, I've added a test separately.

**Pull request merged**
