### PR TITLE
Cisco WebexTeams connector

### PR DESCRIPTION
**Pull request by nahidalam**
**Proposed changes**:
- Created Cisco WebexTeams connector in response to issue #565 

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [x] added some tests for the functionality
- [x] updated connectors.rst to document how to use the WebexTeams connector
- [ ] updated the changelog

### CODE REVIEW

**Comment by akelad** [comment]
@nahidalam thank you so much for your hard work on this PR! We'll review it as soon as possible. In the mean time, the travis build is failing. Could you take a look and fix the issues? 
https://travis-ci.com/RasaHQ/rasa_core/jobs/157122946#L1217
https://travis-ci.com/RasaHQ/rasa_core/jobs/157122946#L1268
https://travis-ci.com/RasaHQ/rasa_core/jobs/157122946#L1457

**Comment by nahidalam** [comment]
@akelad I fixed issues in commit `d73edc6` but the test is failing because

`E   ModuleNotFoundError: No module named 'webexteamssdk'`

So you need to install `webexteamssdk` in your build environment from 

`$ pip install webexteamssdk`

**Comment by nahidalam** [comment]
@akelad so the commit `fecff82` is almost there. Travis build for docs is [failing with message](https://travis-ci.com/RasaHQ/rasa_core/jobs/157378573)

`The command "cd docs && make SPHINXOPTS="-W --keep-going -A html_theme=rasabaster" html" exited with 2.`

But when I run in my local repo 
`cd docs && make SPHINXOPTS="-W --keep-going -A html_theme=rasabaster" html`

the build succeeds 

Any suggestion?

**Comment by akelad** [comment]
screen shot 2018-11-09 at 10 36 21
the issue seems to be with the docs, something about your module not existing

**Comment by nahidalam** [comment]
> screen shot 2018-11-09 at 10 36 21
> the issue seems to be with the docs, something about your module not existing

you are saying this @akelad because of  `no module named webexteamssdk` message? I included `webexteamssdk` in the requirements.txt. Anything else?

**Comment by nahidalam** [comment]
@tmbo any thoughts?

**Comment by nahidalam** [comment]
Ok @akelad Travis is passing.

**Pull request merged**
