### PR TITLE
Only include ner_crf entities in nlu export by including the extractor field in each entity at NLU 

### LINKED ISSUE #1728: Correcting the intent in interactive learning mode removes additional entity information
**Rasa Core version**: 0.13.2
**Python version**: 3.6.8
**Operating system**: windows

When one corrects the intent in the interactive learning mode, but leaves the entities untouched they get altered.

Look at this example:
`Is the NLU classification for '[Am Mittwoch](time:2019-02-20T00:00:00.000+01:00)' with intent 'choose_appointment'`

The date was recognized by duckling. Without altering the intent the entity would get saved as following in the tracker:

```
"entities": [
            {
              "start": 0,
              "end": 11,
              "text": "Am Mittwoch",
              "value": "2019-02-20T00:00:00.000+01:00",
              "confidence": 1,
              "additional_info": {
                "values": [
                  {
                    "value": "2019-02-20T00:00:00.000+01:00",
                    "grain": "day",
                    "type": "value"
                  },
                  {
                    "value": "2019-02-27T00:00:00.000+01:00",
                    "grain": "day",
                    "type": "value"
                  },
                  {
                    "value": "2019-03-06T00:00:00.000+01:00",
                    "grain": "day",
                    "type": "value"
                  }
                ],
                "value": "2019-02-20T00:00:00.000+01:00",
                "grain": "day",
                "type": "value"
              },
              "entity": "time",
              "extractor": "ner_duckling_http"
            }
          ],
```

After altering the recognized intent, but leaving the entity untouched, it gets reduced to:

```
"entities": [
              {
                "end": 11,
                "entity": "time",
                "start": 0,
                "value": "2019-02-20T00:00:00.000+01:00"
              }
            ],
```

### LINKED ISSUE #1732: Interactive Learning: Only include ner_crf entities in nlu export by including the extractor field in each entity at NLU
At the end of interactive learning you can save stories and NLU data which you collected during the training. However, the exported NLU data should only include entity annotation for entities which were 
* extracted by ner_crf
* manually annotated by the user

### PR DESCRIPTION
**Pull request by paulaWesselmann**
**Proposed changes**:
- fixes #1732

**Status (please check what you already did)**:
- [x] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog

### CODE REVIEW

**Comment by paulaWesselmann** [comment]
The second commit fixes #1732, i tested it's functionality. The first commit is addressing this issue specifically, but I didn't test it yet.

**Comment by mauricedoepke** [comment]
Thanks for your help. #1732 Seems to be solved by this. #1728 is technically also solved but there is an edge case which I forgot to mention that is not yet solved.

Suppose I got something like this: 
`Ich brauche [nächste woche freitag](time:2019-02-22T00:00:00.000+01:00) einen [Mietwagen](some_wrong_entity)`
And i correct it to:
`Ich brauche [nächste woche freitag](time:2019-02-22T00:00:00.000+01:00) einen [Mietwagen](right_entity)`
Then the entity information will still be lost. It would be greate if we could correct the entities one by one and only overwrite them, if the text or the value attribute changed.



Does 
`ich brauche [nächste woche freitag](time:2019-02-22T00:00:00.000+01:00)[nächste woche freitag](appointment_positive_preference) einen termin`
get saved as 
`ich brauche [nächste woche freitag](appointment_positive_preference) einen termin`
with this fix? It would be nice to add this as a testcase.

**Comment by paulaWesselmann** [comment]
I'll submit another PR for the #1728 edge case. This PR is only for the #1732 issue now.

**Comment by akelad** [comment]
@paulaWesselmann I think it's fine if you add that to this PR as well, as long as it's not too much hassle

**Comment by paulaWesselmann** [comment]
@akelad everything is included in the PR for #1728, so if that one is reviewed and merged all is included I think.

**Pull request closed without merging**
